version: '3.8'
services:
  game_app:
    image: game
    network_mode: "host"
    command: npm start --port 8080 --dbhost mongodb:27017
    deploy:
      replicas: 3
    restart: always
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    command: mongod --port 27017
    deploy:
      replicas: 3
    ports:
      - "27017:27017"
